from sqlalchemy.orm import Session

from app.models.app_settings import AppSettings


def get_or_create_app_settings(db: Session) -> AppSettings:
    settings = db.query(AppSettings).first()

    if not settings:
        settings = AppSettings(
            hospital_name="RP Diagnosis System",
            logo_path=None,
            support_email=None,
            report_disclaimer=(
                "This report is generated by an AI-assisted system for educational "
                "and decision-support purposes and should not replace clinical judgment."
            ),
            default_report_footer=None,
        )
        db.add(settings)
        db.commit()
        db.refresh(settings)

    return settings