from sqlalchemy import Column, Integer, String, Text

from app.core.database import Base
from app.models.mixins import TimestampMixin


class AppSettings(Base, TimestampMixin):
    __tablename__ = "app_settings"

    id = Column(Integer, primary_key=True, index=True)

    hospital_name = Column(String, nullable=False, default="RP Diagnosis System")
    logo_path = Column(String, nullable=True)
    support_email = Column(String, nullable=True)

    report_disclaimer = Column(
        Text,
        nullable=True,
        default=(
            "This report is generated by an AI-assisted system for educational "
            "and decision-support purposes and should not replace clinical judgment."
        ),
    )
    default_report_footer = Column(Text, nullable=True)